name:                delta
version:             0.0.1.0
github:              "pittma/delta"
license:             MIT
author:              "dan pittman"
maintainer:          "dan@dpitt.me"
copyright:           "dan pittman, 2017"

extra-source-files:
   - readme.md

dependencies:
  - base >= 4.7 && < 5
  - mtl >= 2.2.1 && < 3
  - transformers >= 0.5.2.0 && < 0.6

library:
  source-dirs: src

executables:
  mono-example:
    main:                Mono.hs
    source-dirs:         bin
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - delta
